version: '2'
services:
  db:
    image: postgres:9.4.1
  redis:
    image: redis

  web:
    build: .
    command: bundle exec unicorn -E production -c /eve/config/unicorn.rb
    ports:
      - "3000:8080"
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
    volumes:
      - .:/myapp
  
  worker:
    build: .
    volumes:
      - .:/myapp
    command: bundle exec sidekiq -e production -c 2
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
